/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IEaveIncentivesController } from "./IEaveIncentivesController";

export class IEaveIncentivesControllerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEaveIncentivesController {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IEaveIncentivesController;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "userBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
    ],
    name: "handleAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
